/*
        C-file generated by ezCircuit Image Converter ezBMP
*/
/*
        Image size H = 8    V = 8

        Convert to B/W 1bit/pixel      Total : 8 Bytes
*/
const unsigned char IMG_KakaoTalk_20210623_164642052_02[] = {
0x00,
0x1c,
0x3c,
0x30,
0x30,
0x3c,
0x1c,
0x00
}; 

/*
const unsigned char IMG_KakaoTalk_20210623_164642052_022[] = {
________,
___XXX__,
__XXXX__,
__XX____,
__XX____,
__XXXX__,
___XXX__ 
________,
}; 
*/
