/*
        C-file generated by ezCircuit Image Converter ezBMP
*/
/*
        Image size H = 8    V = 8

        Convert to W/B 1bit/pixel      Total : 8 Bytes
*/
const unsigned char IMG_KakaoTalk_20210623_164642052[] = {
0x00,
0x3c,
0x7e,
0x7e,
0x7e,
0x3c,
0x60,
0x00
}; 

/*
const unsigned char  IMG_KakaoTalk_20210623_1646420522[] = {
________,
__XXXX__,
_XXXXXX_,
_XXXXXX_,
_XXXXXX_,
__XXXX__,
_XX_____,
________
}; 
*/
