/*
        C-file generated by ezCircuit Image Converter ezBMP
*/
/*
        Image size H = 8    V = 8

        Convert to B/W 1bit/pixel      Total : 8 Bytes
*/
const unsigned char IMG_KakaoTalk_20210623_164642052_01[] = {
0x00,
0x7e,
0xff,
0xab,
0xab,
0x7e,
0xe0,
0x00
}; 

/*
const unsigned char IMG_KakaoTalk_20210623_164642052_012[] = {
________
_XXXXXX_,
XXXXXXXX,
X_X_X_XX,
X_X_X_XX,
_XXXXXX_,
XXX_____,
________ 
}; 
*/
