/*
        C-file generated by ezCircuit Image Converter ezBMP
*/
/*
        Image size H = 8    V = 8

        Convert to B/W 1bit/pixel      Total : 8 Bytes
*/
const unsigned char message_8x8[] = {
  0x00,
  0x7e,
  0xff,
  0xab,
  0xab,
  0x7e,
  0xe0,
  0x00
};

/*
  const unsigned char message[] = {
  ________
  _XXXXXX_,
  XXXXXXXX,
  X_X_X_XX,
  X_X_X_XX,
  _XXXXXX_,
  XXX_____,
  ________
  };
*/

const unsigned char call_8x8[] = {
  0x00,
  0x1c,
  0x3c,
  0x30,
  0x30,
  0x3c,
  0x1c,
  0x00
};

/*
  const unsigned char call[] = {
  ________,
  ___XXX__,
  __XXXX__,
  __XX____,
  __XX____,
  __XXXX__,
  ___XXX__
  ________,
  };
*/
//const unsigned char PROGMEM kakaotalk[] = {
const unsigned char kakaotalk_8x8[] = {
  0x00,
  0x3c,
  0x7e,
  0x7e,
  0x7e,
  0x3c,
  0x60,
  0x00
};

/*
  const unsigned char  kakaotalk[] = {
  ________,
  __XXXX__,
  _XXXXXX_,
  _XXXXXX_,
  _XXXXXX_,
  __XXXX__,
  _XX_____,
  ________
  };
*/
